#!/usr/bin/env bash
# dev.sh — develop better-touchbar from this Mac (runs under macOS's bash 3.2).
# Usage:
#   scripts/dev.sh check                          gate: compile, self-tests, layouts, icons, docs
#   scripts/dev.sh deploy <host> [install opts]   gate, ship tracked files, run install.sh there, assert
#   scripts/dev.sh status <host>                  read-only: services, fallback flag, helper, extension, log
#   scripts/dev.sh shot <host> [out.png]          save what the Touch Bar shows right now
#   scripts/dev.sh screenshots <host>             regenerate docs/screenshots (drawn on the Mac)
#   scripts/dev.sh icons                          regenerate icons/ from Material Symbols (K-007)
# <host> is an ~/.ssh/config alias of a T2 MacBook with passwordless sudo. deploy WRITES to it.
set -euo pipefail

REMOTE_DIR=/tmp/better-touchbar
EXT=better-touchbar@kaanergun.github.io
ICON_BASE=https://raw.githubusercontent.com/google/material-design-icons/master
ICONS="settings light_mode backlight_high overview_key apps screenshot_region
  skip_previous play_arrow pause skip_next volume_off volume_up mic mic_off
  wifi wifi_off bluetooth bluetooth_disabled do_not_disturb_on notifications bedtime close
  terminal refresh arrow_back arrow_forward add search content_copy content_paste
  cancel chevron_left chevron_right link keyboard_command_key comment format_align_left
  bug_report backspace"

if [ -t 1 ]; then GREEN=$'\033[32m' YELLOW=$'\033[33m' RED=$'\033[31m' BOLD=$'\033[1m' RESET=$'\033[0m'
else GREEN='' YELLOW='' RED='' BOLD='' RESET=''; fi
step() { printf '\n%s[%s] %s%s\n' "$BOLD" "$1" "$2" "$RESET"; }
ok()   { printf '  %s✅ %s%s\n' "$GREEN" "$*" "$RESET"; }
warn() { printf '  %s⚠️  %s%s\n' "$YELLOW" "$*" "$RESET"; }
fail() { printf '  %s❌ %s%s\n' "$RED" "$*" "$RESET"; exit 1; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"; cd "$SCRIPT_DIR/.."
usage() { sed -n '3,9p' "$SCRIPT_DIR/dev.sh" >&2; exit 1; }

VERB=${1:-}
[ $# -gt 0 ] && shift
HOST=""
need_host() { HOST=${1:-}; [ -n "$HOST" ] || usage; }

ship() {  # only tracked files travel, so nothing untracked (or secret) can reach the Mac
  git ls-files -z | COPYFILE_DISABLE=1 tar --null -T - --no-xattrs --no-mac-metadata -czf - \
    | ssh "$HOST" "rm -rf $REMOTE_DIR && mkdir $REMOTE_DIR && tar -xzf - -C $REMOTE_DIR"
}

gate() {
  step 1/4 "compile"
  python3 -m py_compile touchbar.py tb_hw.py tb_ui.py tb_agent.py cat_art.py tools/*.py
  bash -n install.sh scripts/dev.sh scripts/check.sh
  sh -n system/t2-touchbar-fix
  ok "python, bash and sh parse"

  step 2/4 "self-test (hardware-free: ABI sizes, key table, mapping, layouts, layer logic, cat)"
  python3 touchbar.py --config touchbar.toml --self-test | sed 's/^/  /'

  step 3/4 "layouts and icons"
  python3 - <<'PY'
import glob, json, os, tomllib
PACKAGED = {"brightness_low", "brightness_high", "backlight_low", "backlight_high", "fast_rewind",
            "play_pause", "fast_forward", "volume_off", "volume_down", "volume_up", "mic_off", "search"}
ours = {os.path.basename(p)[:-4] for p in glob.glob("icons/*.svg")}
for p in glob.glob("icons/*.svg"):  # generated by `dev.sh icons`: white-filled single <svg>
    text = open(p).read()
    assert text.startswith('<svg fill="white"') and text.rstrip().endswith("</svg>"), p
json.load(open("gnome-extension/better-touchbar@kaanergun.github.io/metadata.json"))
mine = tomllib.load(open("touchbar.toml", "rb"))
buttons = [b for k in ("control", "compact", "fn") for b in mine[k]] + [b for a in mine["apps"].values() for b in a]
missing = {b["icon"] for b in buttons if "icon" in b} - ours - PACKAGED
assert not missing, f"touchbar.toml icons missing from icons/: {missing}"
fallback = tomllib.load(open("tiny-dfr/config.toml", "rb"))["MediaLayerKeys"]
for key in fallback:  # tiny-dfr fallback layout (K-002)
    assert key.get("Action"), key
    assert "Icon" not in key or key["Icon"] in PACKAGED | ours, f"missing icon {key['Icon']}"
print(f"  {len(buttons)} touchbar.toml buttons, {len(fallback)} fallback keys, {len(ours)} icons")
PY
  ok "every icon exists, extension metadata parses"

  step 4/4 "project docs"
  [ "$(wc -l < CLAUDE.md)" -le 120 ] || fail "CLAUDE.md is longer than 120 lines (~/Developments rule)"
  for doc in development.md dev-log.md docs/PROGRESS.md; do [ -s "$doc" ] || fail "missing $doc"; done
  ok "bundle present, CLAUDE.md $(wc -l < CLAUDE.md | tr -d ' ') lines"

  printf '\n%scheck: OK%s  (not covered here: drawing — install.sh runs --render-test on the Mac)\n' "$GREEN" "$RESET"
}

case $VERB in
check)
  gate
  ;;
deploy)
  need_host "${1:-}"; shift
  step 1/3 "gate"
  gate
  step 2/3 "ship tracked files to $HOST:$REMOTE_DIR"
  ship
  ok "$(git ls-files | wc -l | tr -d ' ') files"
  step 3/3 "install on $HOST"
  ssh "$HOST" "cd $REMOTE_DIR && ./install.sh install $* && rm -rf $REMOTE_DIR"
  state=$(ssh "$HOST" 'systemctl is-active touchbar.service' || true)
  [ "$state" = active ] || fail "touchbar.service is $state on $HOST"
  printf '\n%sdeploy: OK%s  touchbar.service active on %s (evidence: scripts/dev.sh status %s)\n' "$GREEN" "$RESET" "$HOST" "$HOST"
  ;;
status)
  need_host "${1:-}"
  step 1/1 "$HOST (read-only)"
  ssh "$HOST" "EXT=$EXT"' bash -s' <<'SH'
for s in touchbar tiny-dfr t2-touchbar-fix; do printf '  %-18s %s\n' "$s" "$(systemctl is-active $s)"; done
printf '  %-18s %s\n' "fallback flag" "$([ -e /run/touchbar-fallback ] && echo SET || echo no)"
printf '  %-18s %s\n' "session helper" "$(pgrep -fa tb_agent.py | grep -vc runuser || true) running"  # runuser wraps it
uid=$(id -u)
printf '  %-18s %s\n' "focus extension" "$(XDG_RUNTIME_DIR=/run/user/$uid DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$uid/bus gnome-extensions info $EXT 2>/dev/null | awk '/State/{print $2}')"
journalctl -u touchbar -n 5 --no-pager -o cat 2>/dev/null | sed 's/^/  | /'
SH
  ;;
shot)
  need_host "${1:-}"
  out=${2:-touchbar-$(date +%Y%m%d-%H%M%S).png}
  step 1/1 "capture the Touch Bar on $HOST"
  ssh "$HOST" 'sudo -n python3 - /tmp/touchbar-shot.png' < tools/fbshot.py >/dev/null
  scp -q "$HOST:/tmp/touchbar-shot.png" "$out"
  ssh "$HOST" 'sudo -n rm -f /tmp/touchbar-shot.png'
  ok "$out"
  ;;
screenshots)
  need_host "${1:-}"
  step 1/2 "draw every layer on $HOST (the Mac has pycairo, this machine may not)"
  ship
  ssh "$HOST" "cd $REMOTE_DIR && python3 touchbar.py --config touchbar.toml --screenshots $REMOTE_DIR/shots >/dev/null"
  step 2/2 "copy back to docs/screenshots"
  mkdir -p docs/screenshots
  scp -q "$HOST:$REMOTE_DIR/shots/*.png" docs/screenshots/
  ssh "$HOST" "rm -rf $REMOTE_DIR"
  ok "$(ls docs/screenshots/*.png | wc -l | tr -d ' ') PNGs; review with git diff before committing"
  ;;
icons)
  step 1/1 "fetch Material Symbols (Rounded, filled) and recolour white"
  mkdir -p icons
  n=0
  for name in $ICONS; do
    svg=$(curl -fsS "$ICON_BASE/symbols/web/$name/materialsymbolsrounded/${name}_fill1_24px.svg" 2>/dev/null \
       || curl -fsS "$ICON_BASE/symbols/web/$name/materialsymbolsrounded/${name}_24px.svg") \
       || fail "icon $name not found"
    printf '%s\n' "${svg/<svg /<svg fill=\"white\" }" > "icons/$name.svg"
    n=$((n + 1))
  done
  curl -fsS "$ICON_BASE/LICENSE" > icons/LICENSE
  ok "$n icons in icons/ (Apache-2.0, icons/LICENSE); generated files: edit ICONS in this script"
  ;;
*)
  usage
  ;;
esac
